<a href="https://colab.research.google.com/github/MinhNhata/BTVN_1_19146227_MinhNhat/blob/main/ANN_HOALAN_CRABS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import linear_model
from sklearn.linear_model import Perceptron
x= [[0,0],[0,1],[1,0],[1,1]]
t= [0,1,1,1]

model=Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [2]:
x1=[[0.5,0.5],[-0.5,-0.5],[10,2.3],[-1,-2]]
y=model.predict(x1)
model.score(x,y)

0.25

In [3]:
x2 = [[0.5,0.5],[0.5,0],[0,0.5],[0.4,0]]
y1=model.predict(x2)
model.score(x,y1)
print(y1)

[1 0 0 0]


In [4]:
from sklearn.linear_model import Perceptron

x=[[-0.5,-0.5],[-0.5,0.5],[0.3,0.5],[-0.1,1]]
t = [1,1,0,0]


model=Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [5]:
x1= [[0,0],[0,1],[1,0],[1,1]]
y1 = model.predict(x)
model.score(x,y1)
print(y1)

[1 1 0 0]


In [7]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split 

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler


iris = datasets.load_iris()
x= iris.data
y = iris.target
print(x[:5])
print(y[:5])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train)
x_test_std=sc.transform(x_test)
print(x_train_std[:5],x_train[:5])
print(y[:5])

model = Perceptron(max_iter=1000,eta0=0.4,random_state=0)

model.fit(x_train_std,y_train)
y_pred=model.predict(x_test_std)

print(y_pred)
print(y_test)
print("Do chinh xac mo hinh:",accuracy_score(y_test,y_pred))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[[ 1.25484588  0.08982076  0.59829697  0.32833208]
 [-0.09463921  2.21183626 -1.51094416 -1.35021955]
 [-0.58536107  0.79715926 -1.22591157 -1.35021955]
 [ 0.27340217 -0.61751774  0.48428393 -0.05902599]
 [-1.07608292  0.79715926 -1.33992461 -1.35021955]] [[6.9 3.1 4.9 1.5]
 [5.8 4.  1.2 0.2]
 [5.4 3.4 1.7 0.2]
 [6.1 2.8 4.7 1.2]
 [5.  3.4 1.5 0.2]]
[0 0 0 0 0]
[2 1 1 1 1 0 0 1 2 0 0 0 0 0 2 2 1 2 2 2 1 0 1 0 1 0 2 1 1 1 1 0 2 0 2 1 0
 2 2 0 0 2 0 1 0]
[2 2 1 1 1 0 0 1 2 0 0 0 0 0 1 2 1 2 2 2 1 0 1 0 1 0 2 1 1 1 1 0 1 0 2 1 0
 2 2 0 0 2 0 1 0]
Do chinh xac mo hinh: 0.9333333333333333


In [8]:

#CRABS
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
url = '/content/crabs.csv'
DataFrame = pd.read_csv(url)

print(DataFrame)

    speies sex  index  fontallip  rearwidth  length  width  depth
0        B   M      1        8.1        6.7    16.1   19.0    7.0
1        B   M      2        8.8        7.7    18.1   20.8    7.4
2        B   M      3        9.2        7.8    19.0   22.4    7.7
3        B   M      4        9.6        7.9    20.1   23.1    8.2
4        B   M      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   F     46       21.4       18.0    41.2   46.2   18.7
196      O   F     47       21.7       17.1    41.7   47.2   19.6
197      O   F     48       21.9       17.2    42.6   47.4   19.5
198      O   F     49       22.5       17.2    43.0   48.7   19.8
199      O   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [9]:
DataFrame['speies'].replace({"B":"0","O":"1"},inplace=True)
DataFrame['sex'].replace({"F":"0","M":"1"},inplace=True)
print(DataFrame)

    speies sex  index  fontallip  rearwidth  length  width  depth
0        0   1      1        8.1        6.7    16.1   19.0    7.0
1        0   1      2        8.8        7.7    18.1   20.8    7.4
2        0   1      3        9.2        7.8    19.0   22.4    7.7
3        0   1      4        9.6        7.9    20.1   23.1    8.2
4        0   1      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      1   0     46       21.4       18.0    41.2   46.2   18.7
196      1   0     47       21.7       17.1    41.7   47.2   19.6
197      1   0     48       21.9       17.2    42.6   47.4   19.5
198      1   0     49       22.5       17.2    43.0   48.7   19.8
199      1   0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [10]:
DataFrame= datasets.load_iris()
x= DataFrame.data
y = DataFrame.target
print(x[:5])
print(y[:5])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train)
x_test_std=sc.transform(x_test)
print(x_train_std[:5],x_train[:5])
print(y[:5])

model = Perceptron(max_iter=1000,eta0=0.4,random_state=0)

model.fit(x_train_std,y_train)
y_pred=model.predict(x_test_std)

print(y_pred)
print(y_test)
print("Do chinh xac mo hinh:",accuracy_score(y_test,y_pred))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[[-0.81471591 -0.7968363   0.02590507  0.19363274]
 [ 0.15600943 -1.93672475  0.08377809 -0.33445655]
 [-1.17873792  0.11507445 -1.3630474  -1.39063511]
 [-1.54275992  0.11507445 -1.3630474  -1.39063511]
 [-0.32935324 -0.34088093 -0.14771399  0.06161042]] [[5.2 2.7 3.9 1.4]
 [6.  2.2 4.  1. ]
 [4.9 3.1 1.5 0.2]
 [4.6 3.1 1.5 0.2]
 [5.6 2.9 3.6 1.3]]
[0 0 0 0 0]
[1 1 0 2 1 0 1 1 1 2 0 2 0 2 1 1 0 2 1 0 2 0 0 0 0 1 1 0 0 0 0 2 1 2 0 0 2
 2 1 2 0 0 2 1 2]
[1 1 0 2 1 0 1 1 1 1 0 2 0 1 2 1 0 2 1 0 2 0 0 0 0 1 1 0 0 0 0 2 1 2 0 0 2
 2 1 1 0 0 2 1 2]
Do chinh xac mo hinh: 0.9111111111111111
